<?php

use App\Http\Controllers\StudosController;
use App\Http\Controllers\ChatController;
use Illuminate\Support\Facades\Route;

Route::get('/health', [StudosController::class, 'health']);
Route::get('/roles', [StudosController::class, 'roles'])->middleware('throttle:60,1');
Route::get('/schools', [StudosController::class, 'schools'])->middleware('throttle:60,1');
Route::post('/classes', [StudosController::class, 'storeClass'])->middleware('throttle:6,1');
Route::get('/classes/id/{classId}', [StudosController::class, 'classByPublicId'])->middleware('throttle:60,1');
Route::get('/classes/invite/{code}', [StudosController::class, 'classByInvite'])->middleware('throttle:30,1');
Route::post('/classes/join', [StudosController::class, 'joinClass'])->middleware('throttle:10,1');
Route::get('/members/code/{code}', [StudosController::class, 'memberByPersonalCode'])->middleware('throttle:15,1');
Route::get('/members/{member}/connections', [StudosController::class, 'connectionsForMember'])->middleware('throttle:60,1');
Route::post('/connections/request', [StudosController::class, 'requestConnection'])->middleware('throttle:20,1');
Route::post('/connections/{connection}/respond', [StudosController::class, 'respondToConnection'])->middleware('throttle:30,1');
Route::post('/session/login', [StudosController::class, 'loginWithPassword'])->middleware('throttle:5,1');
Route::post('/session/request-code', [StudosController::class, 'requestLoginCode'])->middleware('throttle:3,1');
Route::post('/session/verify-code', [StudosController::class, 'verifyLoginCode'])->middleware('throttle:5,1');
Route::get('/session/me', [StudosController::class, 'sessionMe'])->middleware('throttle:120,1');
Route::get('/overview/stats', [StudosController::class, 'overviewStats'])->middleware('throttle:60,1');
Route::get('/activities', [StudosController::class, 'activities'])->middleware('throttle:40,1');
Route::get('/class-battle', [StudosController::class, 'classBattle'])->middleware('throttle:30,1');
Route::get('/duels', [StudosController::class, 'duels'])->middleware('throttle:60,1');
Route::post('/duels', [StudosController::class, 'storeDuel'])->middleware('throttle:20,1');
Route::post('/duels/{duel}/accept', [StudosController::class, 'acceptDuel'])->middleware('throttle:30,1');
Route::post('/duels/{duel}/decline', [StudosController::class, 'declineDuel'])->middleware('throttle:30,1');
Route::post('/duels/{duel}/cancel', [StudosController::class, 'cancelDuel'])->middleware('throttle:30,1');
Route::post('/duels/{duel}/confirm', [StudosController::class, 'confirmDuel'])->middleware('throttle:30,1');
Route::post('/duels/{duel}/complete', [StudosController::class, 'completeDuel'])->middleware('throttle:30,1');
Route::post('/duels/{duel}/forfeit', [StudosController::class, 'forfeitDuel'])->middleware('throttle:30,1');
Route::post('/duels/{duel}/approve', [StudosController::class, 'approveDuel'])->middleware('throttle:30,1');
Route::post('/duels/{duel}/reject', [StudosController::class, 'rejectDuel'])->middleware('throttle:30,1');
Route::get('/good-deeds/current', [StudosController::class, 'currentGoodDeed'])->middleware('throttle:60,1');
Route::post('/good-deeds/claims', [StudosController::class, 'storeGoodDeedClaim'])->middleware('throttle:20,1');
Route::get('/check-ins/weekly', [StudosController::class, 'weeklyCheckIn'])->middleware('throttle:60,1');
Route::post('/check-ins/weekly', [StudosController::class, 'storeWeeklyCheckIn'])->middleware('throttle:20,1');
Route::post('/notifications/push-token', [StudosController::class, 'registerPushToken'])->middleware('throttle:20,1');
Route::post('/notifications/test', [StudosController::class, 'sendTestNotification'])->middleware('throttle:6,1');
Route::post('/profile/photo', [StudosController::class, 'updateProfilePhoto'])->middleware('throttle:12,1');
Route::post('/members/me/profile', [StudosController::class, 'updateProfile'])->middleware('throttle:20,1');
Route::delete('/members/me', [StudosController::class, 'deleteCurrentAccount'])->middleware('throttle:6,1');
Route::post('/members/me/emergency-contact-visibility', [StudosController::class, 'updateEmergencyContactVisibility'])->middleware('throttle:20,1');
Route::post('/members/me/emergency-contact', [StudosController::class, 'updateEmergencyContact'])->middleware('throttle:20,1');
Route::post('/members/{member}/block', [StudosController::class, 'blockMember'])->middleware('throttle:20,1');
Route::get('/members/me/blocked', [StudosController::class, 'listBlockedMembers'])->middleware('throttle:60,1');
Route::delete('/members/{member}/block', [StudosController::class, 'unblockMember'])->middleware('throttle:20,1');
Route::post('/notifications/push-token/disable', [StudosController::class, 'disablePushToken'])->middleware('throttle:20,1');
Route::get('/notifications/preferences', [StudosController::class, 'getNotificationPreferences'])->middleware('throttle:60,1');
Route::put('/notifications/preferences', [StudosController::class, 'updateNotificationPreferences'])->middleware('throttle:30,1');
Route::post('/classes/{class}/members/{member}/access', [StudosController::class, 'updateMemberAccess'])->middleware('throttle:30,1');
Route::post('/events', [StudosController::class, 'storeEvent'])->middleware('throttle:12,1');
Route::patch('/events/{event}', [StudosController::class, 'updateEvent'])->middleware('throttle:20,1');
Route::delete('/events/{event}', [StudosController::class, 'destroyEvent'])->middleware('throttle:20,1');
Route::post('/events/{event}/update', [StudosController::class, 'updateEvent'])->middleware('throttle:20,1');
Route::post('/events/{event}/delete', [StudosController::class, 'destroyEvent'])->middleware('throttle:20,1');
Route::post('/events/{event}/report', [StudosController::class, 'reportEvent'])->middleware('throttle:10,1');
Route::post('/events/{event}/rsvp', [StudosController::class, 'respondToEvent'])->middleware('throttle:40,1');

Route::get('/galleries', [StudosController::class, 'getGalleries'])->middleware('throttle:40,1');
Route::post('/galleries', [StudosController::class, 'storeGallery'])->middleware('throttle:12,1');
Route::put('/galleries/{gallery}', [StudosController::class, 'updateGallery'])->middleware('throttle:20,1');
Route::delete('/galleries/{gallery}', [StudosController::class, 'destroyGallery'])->middleware('throttle:20,1');
Route::post('/galleries/{gallery}/report', [StudosController::class, 'reportGallery'])->middleware('throttle:10,1');
Route::get('/galleries/{gallery}/photos', [StudosController::class, 'getGalleryPhotos'])->middleware('throttle:60,1');
Route::post('/galleries/{gallery}/photos', [StudosController::class, 'storeGalleryPhoto'])->middleware('throttle:20,1');
Route::get('/gallery-photos/{photo}/download', [StudosController::class, 'downloadGalleryPhoto'])->middleware('throttle:60,1');
Route::delete('/gallery-photos/{photo}', [StudosController::class, 'destroyGalleryPhoto'])->middleware('throttle:20,1');
Route::post('/gallery-photos/{photo}/report', [StudosController::class, 'reportGalleryPhoto'])->middleware('throttle:10,1');

Route::get('/chat/conversations', [ChatController::class, 'conversations']);
Route::post('/chat/realtime/auth', [ChatController::class, 'authorizeRealtimeChannel']);
Route::post('/chat/conversations/direct', [ChatController::class, 'createDirectConversation'])->middleware('throttle:20,1');
Route::post('/chat/conversations/group', [ChatController::class, 'createGroupConversation'])->middleware('throttle:10,1');
Route::get('/chat/conversations/{conversation}/messages', [ChatController::class, 'messages']);
Route::post('/chat/conversations/{conversation}/messages', [ChatController::class, 'sendMessage'])->middleware('throttle:40,1');
Route::post('/chat/conversations/{conversation}/participants', [ChatController::class, 'addGroupParticipants'])->middleware('throttle:10,1');
Route::patch('/chat/conversations/{conversation}', [ChatController::class, 'updateGroupConversation'])->middleware('throttle:10,1');
Route::post('/chat/conversations/{conversation}/read', [ChatController::class, 'markRead']);
Route::post('/chat/conversations/{conversation}/mute', [ChatController::class, 'muteConversation']);
Route::post('/chat/conversations/{conversation}/report', [ChatController::class, 'reportConversation'])->middleware('throttle:10,1');
Route::post('/chat/conversations/{conversation}/block', [ChatController::class, 'blockConversationMember'])->middleware('throttle:10,1');
Route::post('/chat/conversations/{conversation}/hide', [ChatController::class, 'hideConversation']);
Route::post('/chat/conversations/{conversation}/leave', [ChatController::class, 'leaveConversation']);
Route::delete('/chat/conversations/{conversation}', [ChatController::class, 'deleteConversation']);
Route::post('/chat/messages/{message}/report', [ChatController::class, 'reportMessage'])->middleware('throttle:10,1');
Route::delete('/chat/messages/{message}', [ChatController::class, 'deleteMessage']);
