<?php

return [
    'enabled' => env('STUDOS_MODERATION_ENABLED', true),

    'blocked_terms' => [
        'fuck',
        'fucking',
        'bitch',
        'cunt',
        'whore',
        'skank',
        'thot',
        'hoe',
        'hore',
        'luder',
        'kaelling',
        'slutty',
        'din slut',
        'you slut',
        'send nudes',
        'send nude',
        'send nogenbillede',
        'send nogenbilleder',
        'send nogne',
        'vis bryster',
        'vis patter',
        'vis fisse',
        'show tits',
        'show boobs',
        'smash or pass',
        'hot or not',
        'rate hende',
        'rate ham',
        'hvem ville du bolle',
        'ville du bolle',
        'knep hende',
        'knep ham',
        'perker',
        'neger',
        'nigger',
        'nigga',
        'faggot',
        'svans',
        'bosserov',
        'boesserov',
        'retard',
        'spasser',
        'mongo',
        'drab dig selv',
        'draeb dig selv',
        'dod dig selv',
        'doed dig selv',
        'kill yourself',
    ],

    'compact_blocked_terms' => [
        'fuck',
        'luder',
        'kaelling',
        'perker',
        'nigger',
        'nigga',
        'faggot',
        'retard',
        'spasser',
    ],

    'reserved_name_terms' => [
        'studos',
        'admin',
        'administrator',
        'moderator',
        'support',
        'official',
        'officiel',
    ],
];
